[project]
name = "thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.2",
    "ollama>=0.4.7",
    "pandas>=2.2.3",
    "scipy>=1.15.1",
]
